server:
  port: ${server.port}

EPA:
  Deposito:
    Sucursal: ${EPA.Deposito.Sucursal}
    Cajero: ${EPA.Deposito.Cajero}
    OtraCuenta: ${EPA.Deposito.OtraCuenta}
  Compra:
    Fisica: ${EPA.Compra.Fisica}
    Web: ${EPA.Compra.Web}
  Motor_BD: MONGO

spring:
  data:
    mongodb:
      uri: ${mongo.uri}

rabbit:
  uri: ${rabbit.uri}