apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  server.port: "8086"
  EPA.Compra.Fisica: "0.00"
  EPA.Compra.Web: "5.00"
  EPA.Deposito.Cajero: "2.00"
  EPA.Deposito.OtraCuenta: "1.50"
  EPA.Deposito.Sucursal: "0.00"
  rabbit.uri: "amqp://guest:guest@rabbitmq-service:5672"
  mongo.uri: "mongodb://mongo-service:27017/transactions_reactive"